#!/bin/bash

PROGRAM_FILE_NAME=$1
CURRENT_DIR=$(pwd)
PROGRAM_PATH=$CURRENT_DIR/$PROGRAM_FILE_NAME
IMAGE_NAME=${2:-"javiergelatti/simula"}

if tty -s; then
    RUNNING_IN_TERMINAL=true
else
    RUNNING_IN_TERMINAL=false
fi

docker run \
    --volume $PROGRAM_PATH:/simula/program.sim \
    --tty=$RUNNING_IN_TERMINAL \
    --interactive \
    --rm \
    $IMAGE_NAME run_simula
