#!/bin/bash

PROGRAM_NAME="program"

# Compile capturing errors
cim $PROGRAM_NAME &> $PROGRAM_NAME.log

if [ $? -ne 0 ]; then
    # Failed, show compiler output and exit
    cat $PROGRAM_NAME.log
    exit
fi

# Run compiled program
./$PROGRAM_NAME
